spring:
  application:
    name: school-web
  datasource:
    url: jdbc:postgresql://localhost:5432/school-web
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  pagination:
    default:
      page: ${PAGE:1}
      size: ${SIZE:10}
logging:
  level:
    org.hibernate: DEBUG